/**
 * LightTrack TypeScript/JavaScript client — fire-and-forget LLM event ingestion.
 *
 * Wrap your OpenAI / Anthropic / Gemini results and POST a normalized event to the LightTrack API.
 * Best-effort by design: `track*` never throws and never blocks (the POST is not awaited). Uses the
 * global `fetch` (Node 18+ / browsers); zero runtime dependencies. A send that fails is reported via
 * `console.warn` (rate-limited; `LIGHTTRACK_QUIET=1` to silence) rather than vanishing.
 *
 *   import { LightTrack } from "lighttrack-client";
 *   const lt = new LightTrack();                  // LIGHTTRACK_URL + LIGHTTRACK_KEY from env (Node)
 *   const resp = await openai.chat.completions.create(...);
 *   lt.trackOpenAI(resp, { latencyMs: 120 });
 *   await lt.flush();                             // await in-flight sends before exit
 */

import { AdmissionCache, LightTrackBudgetExceeded, viewFromStatuses } from "./admission.ts";
import type { Admit, AdmitQuery, Enforce } from "./admission.ts";
import { Diagnostics, diagnosticKind, noProjectMessage, sendFailureMessage, truncate } from "./diagnostics.ts";
import { parseLimitView } from "./limits.ts";
import { RECOVERED_TAG, SpanJournal, unsettledError } from "./journal.ts";
import { PII_RULES } from "./pii.ts";

export type ProviderName = "openai" | "anthropic" | "google" | (string & {});

export interface TrackOptions {
  /** Use-case / call-site name (e.g. "summarize-email") — the LLM-Overview rollup key. */
  name?: string;
  inputTokens?: number;
  outputTokens?: number;
  cachedInput?: number;
  operation?: "chat" | "completion" | "embedding" | string;
  latencyMs?: number;
  status?: "success" | "error" | "timeout";
  error?: string;
  input?: unknown;
  output?: unknown;
  tags?: string[];
  traceId?: string;
  /** Span id for this call (auto-generated by the instrument wrappers). */
  spanId?: string;
  /** Enclosing span id, so nested agent steps link into a trace tree. */
  parentSpanId?: string;
  metadata?: Record<string, unknown>;
  /** Project id — for dev mode (no key) or an admin key; a project key overrides it server-side. */
  project?: string;
}

export interface LightTrackConfig {
  baseUrl?: string;
  apiKey?: string;
  project?: string;
  source?: string;
  tags?: string[];
  enabled?: boolean;
  timeoutMs?: number;
  /**
   * Suppress the `console.warn` diagnostics a dropped or rejected event otherwise reports.
   * Defaults to the `LIGHTTRACK_QUIET` env var (`1`/`true`/`yes`/`on`).
   */
  quiet?: boolean;
  /**
   * Write a crash-surviving breadcrumb when a span opens, so a process killed mid-call still leaves
   * a record of it (see journal.ts). Defaults on in Node, via `LIGHTTRACK_JOURNAL` (`0` to disable);
   * always a no-op where there is no `node:fs`.
   */
  journal?: boolean;
  /** Where breadcrumbs live. Defaults to `LIGHTTRACK_JOURNAL_DIR`, else a temp subdirectory. A
   * process that may be rescheduled onto fresh storage should point this at a mounted volume, or
   * accept that its in-flight calls are not recoverable. */
  journalDir?: string;
  /**
   * Pre-spend admission (see admission.ts). `"block"` refuses a call the project's caps would turn
   * away, by throwing {@link LightTrackBudgetExceeded} instead of calling the provider; `"warn"`
   * logs and proceeds; `"off"` (the default) only observes. Defaults to `LIGHTTRACK_ENFORCE`.
   *
   * Off by default deliberately: adding an observability SDK must not change what an app does. You
   * opt into having it stop calls.
   */
  enforce?: Enforce;
  /** How long a cached limit view stays evidence, ms. Default 30000. */
  admissionTtlMs?: number;
  /**
   * Record a locally-blocked call as a zero-usage event tagged `lt_blocked_locally`.
   *
   * A blocked call is *not* spend and is never recorded as spend — but it is traffic the app
   * attempted, and a rollup that cannot see it reads as a quiet week rather than a throttled one.
   * Off by default: the event still costs an ingest write against the very cap that refused it.
   */
  recordBlocked?: boolean;
}

const DEFAULT_URL = "http://127.0.0.1:8787";

const PROVIDER_ALIASES: Record<string, string> = {
  openai: "openai", azure: "openai", azure_openai: "openai", oai: "openai",
  anthropic: "anthropic", claude: "anthropic",
  google: "google", gemini: "google", vertex: "google", vertexai: "google", genai: "google",
};

function env(name: string): string | undefined {
  return typeof process !== "undefined" && process.env ? process.env[name] : undefined;
}

function normProvider(p: string): string {
  const s = String(p).trim().toLowerCase();
  return PROVIDER_ALIASES[s] ?? s;
}

function num(v: unknown): number | undefined {
  return typeof v === "number" && isFinite(v) ? v : undefined;
}

/** Extract (model, input, output, cached) from an OpenAI chat/responses object. */
export function extractOpenAI(resp: any): [string | undefined, number, number, number | undefined] {
  const u = resp?.usage ?? {};
  const input = num(u.prompt_tokens) ?? num(u.input_tokens) ?? 0;
  const output = num(u.completion_tokens) ?? num(u.output_tokens) ?? 0;
  // The Responses API renamed the pair AND moved the cache counter: `input_tokens_details`, not
  // `prompt_tokens_details`. Reading only the older place reported every cached Responses call as
  // uncached, which the price book then charged at full input rate.
  const cached = num(u.prompt_tokens_details?.cached_tokens) ?? num(u.input_tokens_details?.cached_tokens);
  return [resp?.model, input, output, cached];
}

/** Extract (model, input, output, cached) from an Anthropic messages object. */
export function extractAnthropic(resp: any): [string | undefined, number, number, number | undefined] {
  const u = resp?.usage ?? {};
  return [resp?.model, num(u.input_tokens) ?? 0, num(u.output_tokens) ?? 0, num(u.cache_read_input_tokens)];
}

/** Extract (model, input, output, cached) from a Gemini generateContent object. */
export function extractGemini(resp: any): [string | undefined, number, number, number | undefined] {
  const u = resp?.usageMetadata ?? resp?.usage_metadata ?? {};
  const input = num(u.promptTokenCount) ?? num(u.prompt_token_count) ?? 0;
  const output = num(u.candidatesTokenCount) ?? num(u.candidates_token_count) ?? 0;
  const cached = num(u.cachedContentTokenCount) ?? num(u.cached_content_token_count);
  return [resp?.modelVersion ?? resp?.model_version, input, output, cached];
}

// ---- Output guardrails -----------------------------------------------------

export interface GuardRules {
  /** Output must parse as JSON. */
  json?: boolean;
  /** Required top-level JSON keys (implies `json`). */
  jsonKeys?: string[];
  maxWords?: number;
  minWords?: number;
  maxChars?: number;
  /** Substrings that must all appear. */
  mustInclude?: string[];
  /** Output must match this pattern. */
  mustMatch?: RegExp | string;
  /** Output must NOT match any of these (banned content / patterns). */
  mustNotMatch?: Array<RegExp | string>;
  /**
   * Reject PII. The rules are the *server's* — generated from `lighttrack_anon`'s scrubber into
   * `clients/contract/fixtures/pii.json` (see pii.ts), so this guard cannot contradict what the
   * ingest path would redact. Kinds: `email`, `iban`, `ssn`, `secret`, `phone`, `credit_card`, `ip`.
   */
  noPII?: boolean;
}

export interface GuardResult {
  ok: boolean;
  violations: string[];
  checks: Record<string, boolean>;
}

/** Compiled once. `PII_RULES` is generated from the server's own scrubber (see pii.ts). */
const PII_COMPILED: Array<[string, RegExp]> = PII_RULES.map((r) => [r.kind, new RegExp(r.pattern)]);

/**
 * The PII families present in `text`, in rule order, each reported once.
 *
 * A kind is a family, not a regex: a phone number has three shapes and a secret three prefixes, and
 * a caller wants to know *a phone number leaked*, not which of three patterns noticed.
 */
export function piiKinds(text: string): string[] {
  const found: string[] = [];
  for (const [kind, re] of PII_COMPILED) {
    if (!found.includes(kind) && re.test(text)) found.push(kind);
  }
  return found;
}

/**
 * Deterministic, network-free output validation — runs inline in the request path. Pure: it returns
 * a verdict; the caller decides what to do (retry / fallback / block). Catches the failure classes
 * LLMs slip on (bad JSON, length/format violations, leaked PII, banned content).
 */
export function guard(output: string, rules: GuardRules): GuardResult {
  const violations: string[] = [];
  const checks: Record<string, boolean> = {};
  const fail = (k: string, msg: string) => {
    checks[k] = false;
    violations.push(msg);
  };
  const ok = (k: string) => {
    checks[k] = true;
  };

  const wantJson = rules.json || (rules.jsonKeys?.length ?? 0) > 0;
  let parsed: any;
  if (wantJson) {
    try {
      parsed = JSON.parse(output.trim());
      ok("json");
    } catch {
      fail("json", "output is not valid JSON");
    }
  }
  if (rules.jsonKeys && parsed && typeof parsed === "object") {
    for (const k of rules.jsonKeys) {
      k in parsed ? ok(`key:${k}`) : fail(`key:${k}`, `missing required JSON key '${k}'`);
    }
  }

  const words = output.trim() ? output.trim().split(/\s+/).length : 0;
  if (rules.maxWords != null) {
    words <= rules.maxWords ? ok("max_words") : fail("max_words", `too long: ${words} words > ${rules.maxWords}`);
  }
  if (rules.minWords != null) {
    words >= rules.minWords ? ok("min_words") : fail("min_words", `too short: ${words} words < ${rules.minWords}`);
  }
  if (rules.maxChars != null) {
    output.length <= rules.maxChars ? ok("max_chars") : fail("max_chars", `too long: ${output.length} chars > ${rules.maxChars}`);
  }
  for (const s of rules.mustInclude ?? []) {
    output.includes(s) ? ok(`include:${s}`) : fail(`include:${s}`, `must include "${s}"`);
  }
  if (rules.mustMatch != null) {
    const src = typeof rules.mustMatch === "string" ? rules.mustMatch : rules.mustMatch.source;
    const re = typeof rules.mustMatch === "string" ? new RegExp(rules.mustMatch) : rules.mustMatch;
    re.test(output) ? ok("must_match") : fail("must_match", `must match ${src}`);
  }
  for (const pat of rules.mustNotMatch ?? []) {
    // Keyed on the PATTERN, not the stringified RegExp: `/nope/` is a JavaScript spelling no other
    // SDK can produce, and a check key that differs by language is not a shared contract.
    const src = typeof pat === "string" ? pat : pat.source;
    const re = typeof pat === "string" ? new RegExp(pat) : pat;
    re.test(output) ? fail(`not_match:${src}`, `must not match ${src}`) : ok(`not_match:${src}`);
  }
  if (rules.noPII) {
    const kinds = piiKinds(output);
    for (const kind of kinds) fail(`pii:${kind}`, `contains ${kind}-like PII`);
    if (kinds.length === 0) ok("no_pii");
  }

  return { ok: violations.length === 0, violations, checks };
}

export interface RelayTaskOptions {
  payload?: unknown;
  /** Dedupe key, unique per project — re-enqueueing returns the existing task. */
  idempotencyKey?: string;
  source?: string;
  maxAttempts?: number;
  retryIntervalSecs?: number;
  project?: string;
}

/**
 * What the enqueue door decided about a task (M18): is there anything out there that could run it?
 *
 * Only `queued` is ever seen on a returned task — a refusal arrives as a thrown {@link RelayError}
 * with `code === "relay_unroutable"`. `eligible_devices` is how much of the fleet advertises this
 * action type; `0` means no devices are enrolled at all (the legacy single-device deployment), not
 * that an enrolled fleet declined it.
 */
export interface RelayAdmission {
  verdict: "queued" | "refused";
  eligible_devices?: number;
  reason?: string;
}

/** A relay task as returned by the API (see docs/RELAY.md). */
export interface RelayTask {
  id: string;
  project_id: string;
  action_type: string;
  status: "queued" | "leased" | "succeeded" | "dead" | "cancelling" | "cancelled";
  attempts: number;
  max_attempts: number;
  result?: unknown;
  error?: string;
  /** Present on the response to `relayTask` (M18); absent on a task fetched later. */
  admission?: RelayAdmission;
  [k: string]: unknown;
}

/**
 * A relay call failed (network error or non-2xx). Relay calls are functional — they throw.
 *
 * `code` carries the API's own error code when the response had one, so a caller can act on the
 * *kind* of failure instead of pattern-matching a message. The one worth branching on is
 * `relay_unroutable` ({@link RelayError.isUnroutable}): no enrolled device advertises that action
 * type, so unlike a timeout or a 503 the call will not succeed on a retry — the fix is the action's
 * spelling, or a device's capabilities.
 */
export class RelayError extends Error {
  /** The API error code (e.g. `relay_unroutable`), when the response carried one. */
  readonly code?: string;
  /** The HTTP status, when the failure was a response rather than a transport error. */
  readonly status?: number;

  constructor(message: string, opts: { code?: string; status?: number } = {}) {
    super(message);
    this.code = opts.code;
    this.status = opts.status;
  }

  /** Whether this is the permanent refusal: nothing in the fleet can ever run that action type. */
  get isUnroutable(): boolean {
    return this.code === "relay_unroutable";
  }
}

/**
 * The API's error code out of an error body, or `undefined` when the body is not one.
 *
 * Deliberately total: an error response is exactly when a body is least likely to be well-formed
 * (a proxy's HTML, a truncated stream), and a parse failure here must degrade to "no code" rather
 * than replace the real failure with a JSON error nobody can act on.
 */
export function errorCode(body: string): string | undefined {
  try {
    const code = (JSON.parse(body) as { error?: { code?: unknown } })?.error?.code;
    return typeof code === "string" ? code : undefined;
  } catch {
    return undefined;
  }
}

export class LightTrack {
  private baseUrl: string;
  private apiKey?: string;
  private project?: string;
  private source?: string;
  private defaultTags: string[];
  private enabled: boolean;
  private timeoutMs: number;
  private inflight: Set<Promise<void>> = new Set();
  /** Rate-limited failure reporting (see diagnostics.ts). Exposed for tests / custom silencing. */
  readonly diag: Diagnostics;
  /** Crash-surviving breadcrumbs for in-flight calls (see journal.ts). Exposed so `Span` and any
   * host-side wrapper can open and retire one. */
  readonly journal: SpanJournal;
  /**
   * The startup sweep for calls a PREVIOUS process began and never settled, resolving with how many
   * were re-reported. Exposed (rather than fired and forgotten) so a caller that needs the recovery
   * to have landed — a test, or a supervisor draining a crashed worker's journal — can await it.
   */
  readonly recovered: Promise<number>;
  /**
   * What the server last said about this project's caps, and the pre-spend verdict taken from it.
   * Exposed so a host app can ask `lt.limits.admit(...)` directly, or seed it in a test.
   */
  readonly limits: AdmissionCache;
  private enforce: Enforce;
  private recordBlocked: boolean;
  /** In-flight `GET /v1/limits/status` refresh, so a stale view triggers one poll, not a stampede. */
  private refreshing?: Promise<void>;

  constructor(cfg: LightTrackConfig = {}) {
    this.baseUrl = (cfg.baseUrl ?? env("LIGHTTRACK_URL") ?? DEFAULT_URL).replace(/\/+$/, "");
    this.apiKey = cfg.apiKey ?? env("LIGHTTRACK_KEY");
    this.project = cfg.project ?? env("LIGHTTRACK_PROJECT");
    this.source = cfg.source;
    this.defaultTags = cfg.tags ?? [];
    this.enabled = cfg.enabled ?? true;
    this.timeoutMs = cfg.timeoutMs ?? 2000;
    this.diag = new Diagnostics({ quiet: cfg.quiet });
    this.journal = new SpanJournal({ enabled: cfg.journal, dir: cfg.journalDir });
    this.enforce = cfg.enforce ?? (env("LIGHTTRACK_ENFORCE") as Enforce | undefined) ?? "off";
    this.recordBlocked = cfg.recordBlocked ?? false;
    this.limits = new AdmissionCache({ ttlMs: cfg.admissionTtlMs });
    // Report the calls a PREVIOUS process began and never settled, before anything else this client
    // sends. That is the whole point of the journal: a later client on the same machine is what
    // turns a killed process's in-flight calls back into records.
    this.recovered = this.enabled ? this.recoverUnsettledSpans() : Promise.resolve(0);
  }

  /**
   * Turn every abandoned journal breadcrumb into a real event; resolves with how many were sent.
   *
   * Runs automatically at construction; exposed so a supervisor that never constructs a client in
   * the crashed process's place can still drain the journal. The emitted event says
   * `status: "error"` with an explicit unsettled reason — never `success`, and never a fabricated
   * zero-token, zero-cost call, because nothing reported an outcome (the world stopped).
   */
  async recoverUnsettledSpans(): Promise<number> {
    let sent = 0;
    let records: Awaited<ReturnType<SpanJournal["recover"]>>;
    try {
      records = await this.journal.recover();
    } catch {
      return 0;
    }
    for (const rec of records) {
      this.track(rec.p ?? "unknown", rec.m, {
        name: rec.n,
        operation: rec.op,
        status: "error",
        error: unsettledError(rec),
        traceId: rec.tr,
        spanId: rec.sp,
        parentSpanId: rec.ps,
        project: rec.pj,
        tags: [RECOVERED_TAG],
      });
      sent += 1;
    }
    if (sent) {
      this.diag.warn(
        "unsettled-spans",
        `recovered ${sent} call(s) that began but never reported an outcome (a previous process was ` +
          `killed mid-call). They are recorded with status=error and the '${RECOVERED_TAG}' tag; ` +
          `their token counts and cost are unknown, not zero.`,
      );
    }
    return sent;
  }

  /** Record one LLM call. Returns immediately; the send is fire-and-forget. */
  track(provider: ProviderName, model: string | undefined, opts: TrackOptions = {}): void {
    if (!this.enabled) return;
    const usage: Record<string, number> = {
      input: Math.trunc(opts.inputTokens ?? 0),
      output: Math.trunc(opts.outputTokens ?? 0),
    };
    if (opts.cachedInput != null) usage.cached_input = Math.trunc(opts.cachedInput);

    const ev: Record<string, unknown> = {
      provider: normProvider(provider),
      model: model ?? "unknown",
      usage,
    };
    const pid = opts.project ?? this.project;
    if (pid) ev.project_id = pid;
    if (opts.name) ev.name = opts.name;
    if (opts.operation) ev.operation = opts.operation;
    if (opts.latencyMs != null) ev.latency_ms = Math.trunc(opts.latencyMs);
    let status = opts.status;
    if (opts.error) {
      ev.error = opts.error;
      status = status ?? "error";
    }
    if (status) ev.status = status;
    if (opts.input !== undefined) ev.input = opts.input;
    if (opts.output !== undefined) ev.output = opts.output;
    const tags = [...this.defaultTags, ...(opts.tags ?? [])];
    if (tags.length) ev.tags = tags;
    if (opts.traceId) ev.trace_id = opts.traceId;
    if (opts.spanId) ev.span_id = opts.spanId;
    if (opts.parentSpanId) ev.parent_span_id = opts.parentSpanId;
    if (this.source) ev.source = this.source;
    if (opts.metadata) ev.metadata = opts.metadata;

    this.post("/v1/events", ev);
  }

  trackOpenAI(response: any, opts: TrackOptions = {}): void {
    const [model, input, output, cached] = extractOpenAI(response);
    this.track("openai", model, { inputTokens: input, outputTokens: output, cachedInput: cached, ...opts });
  }

  trackAnthropic(response: any, opts: TrackOptions = {}): void {
    const [model, input, output, cached] = extractAnthropic(response);
    this.track("anthropic", model, { inputTokens: input, outputTokens: output, cachedInput: cached, ...opts });
  }

  trackGemini(response: any, model?: string, opts: TrackOptions = {}): void {
    const [m, input, output, cached] = extractGemini(response);
    this.track("google", model ?? m, { inputTokens: input, outputTokens: output, cachedInput: cached, ...opts });
  }

  /**
   * Validate an output inline against deterministic {@link guard} rules and record the verdict to
   * LightTrack (fire-and-forget) as a score, so guardrail pass-rates are observable. Returns the
   * verdict so the caller can act (retry / fallback / block). Never blocks or throws.
   */
  trackGuard(output: string, rules: GuardRules, opts: { project?: string; name?: string } = {}): GuardResult {
    const result = guard(output, rules);
    if (this.enabled) {
      const score: Record<string, unknown> = {
        rubric: opts.name ? `guard:${opts.name}` : "guard",
        value: result.ok ? 1 : 0,
        max: 1,
        pass: result.ok,
        reasoning: result.violations.join("; ") || "all checks passed",
        scored_by: this.source ? `guard:${this.source}` : "lighttrack-guard",
      };
      const pid = opts.project ?? this.project;
      if (pid) score.project_id = pid;
      this.post("/v1/scores", score);
    }
    return result;
  }

  /** Time a call and track on `end()`: `const s = lt.span("openai","gpt-4o"); ...; s.endOpenAI(resp)`. */
  span(provider: ProviderName, model?: string, opts: TrackOptions = {}): Span {
    return new Span(this, provider, model, opts);
  }

  // ---- relay (cloud→device tasks; docs/RELAY.md) ----

  /**
   * Enqueue a task for the enrolled local device (executed via Claude Code, offline-tolerant).
   * Unlike `track*`, this is a functional call: it awaits the response and throws {@link RelayError}
   * on failure.
   */
  async relayTask(actionType: string, opts: RelayTaskOptions = {}): Promise<RelayTask> {
    const body: Record<string, unknown> = { action_type: actionType };
    if (opts.payload !== undefined) body.payload = opts.payload;
    if (opts.idempotencyKey) body.idempotency_key = opts.idempotencyKey;
    const source = opts.source ?? this.source;
    if (source) body.source = source;
    if (opts.maxAttempts != null) body.max_attempts = Math.trunc(opts.maxAttempts);
    if (opts.retryIntervalSecs != null) body.retry_interval_secs = Math.trunc(opts.retryIntervalSecs);
    const pid = opts.project ?? this.project;
    if (pid) body.project_id = pid;
    return (await this.request("POST", "/v1/relay/tasks", body)) as RelayTask;
  }

  /** Fetch one relay task (status / result / error). Throws {@link RelayError} on failure. */
  async getRelayTask(taskId: string): Promise<RelayTask> {
    return (await this.request("GET", `/v1/relay/tasks/${taskId}`)) as RelayTask;
  }

  /**
   * Poll until the task settles (`succeeded` | `dead`) or `timeoutMs` elapses; resolves with the
   * last seen task either way. Relay work is offline-tolerant by design — retries may span 5h
   * windows — so only wait on tasks the device is expected to pick up promptly.
   */
  async waitRelayTask(
    taskId: string,
    opts: { timeoutMs?: number; intervalMs?: number } = {},
  ): Promise<RelayTask> {
    const deadline = Date.now() + (opts.timeoutMs ?? 1_200_000);
    const interval = opts.intervalMs ?? 15_000;
    for (;;) {
      const task = await this.getRelayTask(taskId);
      if (task.status === "succeeded" || task.status === "dead" || Date.now() >= deadline) {
        return task;
      }
      await new Promise((r) => setTimeout(r, Math.min(interval, Math.max(0, deadline - Date.now()))));
    }
  }

  /**
   * Would a call be admitted right now? Pure and instant — decided from the last ingest response
   * this client saw, with no round trip (see admission.ts).
   */
  admit(q: AdmitQuery = {}): Admit {
    return this.limits.admit(q);
  }

  /**
   * The enforcement gate the instrumentation wrappers call before a provider call.
   *
   * Throws {@link LightTrackBudgetExceeded} under `enforce: "block"`, warns under `"warn"`, and is
   * a no-op under `"off"`. A stale view kicks off one background refresh and still admits — the
   * decision never waits on the network.
   */
  gate(name?: string): void {
    if (this.enforce === "off" || !this.enabled) return;
    // The server mints the event id, so the client cannot know it in advance: this is a fresh
    // ticket per call. The shed *rate* therefore matches the server's; the shed *set* does not.
    // Proportional local shedding is the honest thing this can deliver, and saying so is better
    // than implying an agreement that only holds when the caller supplies the id itself.
    const verdict = this.limits.admit({ name, eventId: ticketId() });
    if (verdict.stale) void this.refreshLimits();
    if (verdict.ok) return;
    if (this.recordBlocked) this.recordBlockedCall(name, verdict);
    const msg = `LightTrack: ${name ?? "this call"} refused before it was made (${verdict.reason})`;
    if (this.enforce === "warn") {
      this.diag.warn("budget", `${msg}. enforce="warn", so the call is proceeding anyway.`);
      return;
    }
    throw new LightTrackBudgetExceeded(verdict, `Use enforce: "warn" to log instead of throwing.`);
  }

  /** Record a call this client refused: real traffic, zero usage, and explicitly not spend. */
  private recordBlockedCall(name: string | undefined, verdict: Admit): void {
    this.track("lighttrack", "blocked", {
      name,
      status: "error",
      error: `blocked locally by pre-spend admission (${verdict.reason})`,
      tags: [BLOCKED_TAG],
      metadata: { lt_admit_reason: verdict.reason, lt_retry_after_secs: verdict.retryAfterSecs },
    });
  }

  /**
   * Refresh the limit view from `GET /v1/limits/status`. Best-effort and deduplicated: a burst of
   * stale verdicts triggers one poll, and a failure leaves the old view in place (fail open).
   */
  async refreshLimits(): Promise<void> {
    if (this.refreshing) return this.refreshing;
    this.refreshing = (async () => {
      try {
        const q = this.project ? `?project=${encodeURIComponent(this.project)}` : "";
        const body = (await this.request("GET", `/v1/limits/status${q}`)) as any;
        const view = viewFromStatuses(body?.statuses);
        if (view) this.limits.observe(view);
      } catch {
        /* best-effort: an unreachable status endpoint must not change what the app does */
      } finally {
        this.refreshing = undefined;
      }
    })();
    return this.refreshing;
  }

  /** Await all in-flight sends (call before process exit). */
  async flush(): Promise<void> {
    await Promise.allSettled([...this.inflight]);
  }

  /** Orderly shutdown: drain in-flight sends, then retire this process's journal. The stale window
   * exists to detect crashes; paying it on a clean exit is pure waste. */
  async close(): Promise<void> {
    await this.flush();
    this.journal.close();
  }

  /** Synchronous-style request for functional calls (relay): returns parsed JSON, throws on error. */
  private async request(method: string, path: string, body?: Record<string, unknown>): Promise<unknown> {
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (this.apiKey) headers["Authorization"] = `Bearer ${this.apiKey}`;
    let resp: Response;
    try {
      resp = await fetch(`${this.baseUrl}${path}`, {
        method,
        headers,
        body: body ? JSON.stringify(body) : undefined,
      });
    } catch (e) {
      throw new RelayError(`${method} ${path} failed: ${e}`);
    }
    const text = await resp.text();
    if (!resp.ok) {
      throw new RelayError(`${method} ${path} -> HTTP ${resp.status}: ${text}`, {
        code: errorCode(text),
        status: resp.status,
      });
    }
    try {
      return JSON.parse(text);
    } catch {
      throw new RelayError(`${method} ${path}: response is not JSON`);
    }
  }

  /**
   * Best-effort POST: the promise is never awaited by the caller and never rejects into the host
   * app — but a failure is reported (rate-limited, per error kind) instead of vanishing.
   */
  private post(path: string, body: Record<string, unknown>): void {
    const hasProject = Boolean(body.project_id);
    const hasKey = Boolean(this.apiKey);
    // Catch the misconfiguration that is guaranteed to fail *before* spending a round trip on it:
    // no project and no API key means the server has no way to attribute the event and will 400.
    if (!hasProject && !hasKey) this.diag.warn("no-project", noProjectMessage(this.baseUrl));

    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (this.apiKey) headers["Authorization"] = `Bearer ${this.apiKey}`;
    const ac = typeof AbortController !== "undefined" ? new AbortController() : undefined;
    const timer = ac ? setTimeout(() => ac.abort(), this.timeoutMs) : undefined;
    const p = fetch(`${this.baseUrl}${path}`, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal: ac?.signal,
    })
      .then(async (resp) => {
        let text = "";
        try {
          text = await resp.text();
        } catch {
          /* body unreadable (aborted / already consumed) — the status alone is still actionable */
        }
        // Every ingest response, accepted or refused, is evidence about the project's position.
        // Reading it here is what makes `admit()` answer from the wall the app is actually near.
        this.observeLimits(resp.status, resp.headers, text);
        if (resp.ok) return;
        const detail = truncate(text);
        this.diag.warn(
          diagnosticKind(resp.status),
          sendFailureMessage(this.baseUrl, path, `HTTP ${resp.status} ${detail}`, {
            status: resp.status,
            hasProject,
            hasKey,
          }),
        );
      })
      .catch((e: unknown) => {
        // A timeout aborts the request; report it as its own kind so it doesn't hide behind (or
        // crowd out) genuine connection failures.
        const aborted = (e as { name?: string })?.name === "AbortError";
        const detail = aborted ? `timed out after ${this.timeoutMs}ms` : String(e);
        this.diag.warn(diagnosticKind(undefined, { timedOut: aborted }), sendFailureMessage(this.baseUrl, path, detail, { hasProject, hasKey }));
      })
      .finally(() => {
        if (timer) clearTimeout(timer);
        this.inflight.delete(p);
      });
    this.inflight.add(p);
  }

  /** Fold one ingest response into the admission cache. Never throws into the send path. */
  private observeLimits(status: number, headers: Headers, text: string): void {
    try {
      let body: unknown;
      try {
        body = text ? JSON.parse(text) : undefined;
      } catch {
        /* a proxy's HTML, a truncated stream — the status and headers still carry the signal */
      }
      this.limits.observe(parseLimitView(status, headers, body));
    } catch {
      /* observing must never break a send */
    }
  }
}

/** Tag on the zero-usage event a locally-blocked call leaves behind. */
export const BLOCKED_TAG = "lt_blocked_locally";

/** A throwaway id for one shed-lottery draw. Not the event id — the server mints that. */
function ticketId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * A call in flight.
 *
 * The event is still sent on `end()` — that is when the usage and the outcome are known. What
 * changed: construction also writes a crash-surviving breadcrumb (see journal.ts), so a process
 * killed between `span()` and `end()` no longer erases the call entirely. `end()` retires it.
 */
export class Span {
  private client: LightTrack;
  private provider: ProviderName;
  private opts: TrackOptions;
  private startedAt: number;
  private usage: { inputTokens: number; outputTokens: number; cachedInput?: number } = {
    inputTokens: 0,
    outputTokens: 0,
  };
  private model?: string;
  private journalKey?: number;

  constructor(client: LightTrack, provider: ProviderName, model: string | undefined, opts: TrackOptions) {
    this.client = client;
    this.provider = provider;
    this.opts = opts;
    this.model = model;
    this.startedAt = Date.now();
    this.journalKey = client.journal.begin({
      p: provider,
      m: model,
      n: opts.name,
      op: opts.operation,
      tr: opts.traceId,
      sp: opts.spanId,
      ps: opts.parentSpanId,
      pj: opts.project,
      t: this.startedAt,
    });
  }

  setUsage(inputTokens: number, outputTokens: number, cachedInput?: number): this {
    this.usage = { inputTokens, outputTokens, cachedInput };
    return this;
  }

  setOpenAI(resp: any): this {
    const [m, i, o, c] = extractOpenAI(resp);
    this.model = this.model ?? m;
    return this.setUsage(i, o, c);
  }

  setAnthropic(resp: any): this {
    const [m, i, o, c] = extractAnthropic(resp);
    this.model = this.model ?? m;
    return this.setUsage(i, o, c);
  }

  setGemini(resp: any): this {
    const [m, i, o, c] = extractGemini(resp);
    this.model = this.model ?? m;
    return this.setUsage(i, o, c);
  }

  /** Finish the span: measure latency and track. Pass an error to record a failed call. */
  end(error?: unknown): void {
    try {
      this.client.track(this.provider, this.model, {
        ...this.opts,
        latencyMs: Date.now() - this.startedAt,
        inputTokens: this.usage.inputTokens,
        outputTokens: this.usage.outputTokens,
        cachedInput: this.usage.cachedInput,
        status: error ? "error" : this.opts.status,
        error: error ? String(error) : this.opts.error,
      });
    } finally {
      // Retired on EVERY exit path, success or failure. An unretired breadcrumb would resurface
      // later as a phantom unsettled call — the measuring instrument lying in the other direction.
      this.client.journal.settle(this.journalKey);
      this.journalKey = undefined;
    }
  }
}

// Rate-limited failure reporting (see diagnostics.ts) — exported so a host app can inspect or reuse it.
export { Diagnostics, diagnosticKind, noProjectMessage, sendFailureMessage } from "./diagnostics.ts";

// The server's PII rule set, generated from crates/anon (see pii.ts).
export { PII_RULES } from "./pii.ts";
export type { PiiRule } from "./pii.ts";

// Pre-spend admission: acting on those signals before the call (see admission.ts).
export {
  AdmissionCache,
  LightTrackBudgetExceeded,
  shedTicket,
  viewFromStatuses,
  DEFAULT_ADMISSION_TTL_MS,
} from "./admission.ts";
export type { Admit, AdmitQuery, AdmitReason, Enforce } from "./admission.ts";

// Reading an ingest response's limit signals (see limits.ts).
export { parseLimitView } from "./limits.ts";
export type { LimitView, BindingScope } from "./limits.ts";

// Crash-surviving breadcrumbs for in-flight calls (see journal.ts).
export { SpanJournal, unsettled, unsettledError, RECOVERED_TAG, DEFAULT_ORPHAN_MS } from "./journal.ts";
export type { JournalRecord, SpanJournalOptions } from "./journal.ts";

// One-line auto-instrumentation + trace-context propagation (see instrument.ts).
export {
  wrap,
  wrapOpenAI,
  wrapAnthropic,
  wrapGemini,
  withTrace,
  withSpan,
  currentTraceId,
  currentSpanId,
  randomId,
} from "./instrument.ts";
