-- generated by `cargo test -p lighttrack-store --test schema_doc` — do not edit by hand.
-- The source of truth is the declarative model in crates/store/src/schema/tables/.
-- Regenerate with `UPDATE_SCHEMA_SQL=1 cargo test -p lighttrack-store --test schema_doc`.
--
-- LightTrack local store (SQLite), the reference schema. Columns added after a table
-- shipped are NOT written here: they are applied as ALTER TABLE … ADD COLUMN by
-- crate::sqlite::schema::apply, from the same model, so a database created today and one
-- created five milestones ago converge on the same shape.
PRAGMA journal_mode = WAL;

-- A tenant. Everything else in the schema hangs off a project id.
CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  -- none | hash | drop
  redaction TEXT NOT NULL DEFAULT 'none',
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id),
  name TEXT NOT NULL,
  prefix TEXT NOT NULL,
  key_hash TEXT NOT NULL,
  created_at TEXT NOT NULL,
  last_used_at TEXT,
  revoked INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_api_keys_prefix ON api_keys(prefix);

-- One observed LLM call. The ingest table; everything cost-shaped is a rollup of it.
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  trace_id TEXT,
  span_id TEXT,
  parent_span_id TEXT,
  ts TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  operation TEXT NOT NULL DEFAULT 'chat',
  input_tokens INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  cached_input_tokens INTEGER,
  reasoning_tokens INTEGER,
  cost_usd REAL,
  latency_ms INTEGER,
  status TEXT NOT NULL DEFAULT 'success',
  error TEXT,
  input TEXT,
  output TEXT,
  -- JSON array
  tags TEXT,
  source TEXT,
  metadata TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_project_ts ON events(project_id, ts);
-- Windowed accounting (usage_since / usage_since_scoped / the daily forecast series) filters on
-- server arrival time, not client `ts`. Postgres indexes the *expression the queries use*: a
-- plain (project_id, received_at) index cannot serve `COALESCE(received_at, ts) >= $2`, and
-- admission runs that query on every ingested event inside the per-project admission lock.
CREATE INDEX IF NOT EXISTS idx_events_project_received ON events(project_id, received_at);
CREATE INDEX IF NOT EXISTS idx_events_trace ON events(trace_id);
-- The project-scoped trace rollup (list_trace_summaries): filter project_id + group by trace_id
-- without a full scan. Single-column idx_events_trace still serves the project-agnostic
-- per-trace fetch.
CREATE INDEX IF NOT EXISTS idx_events_project_trace ON events(project_id, trace_id);
CREATE INDEX IF NOT EXISTS idx_events_project_name_ts ON events(project_id, name, ts);
-- Composites for the high-cardinality event-list predicates. Each puts the filtered column
-- ahead of `ts` so one index serves BOTH the equality seek and the `ORDER BY ts DESC` keyset
-- paging. NOT declared on Postgres today — see the model.
CREATE INDEX IF NOT EXISTS idx_events_project_provider_ts ON events(project_id, provider, ts);
CREATE INDEX IF NOT EXISTS idx_events_project_model_ts ON events(project_id, model, ts);
CREATE INDEX IF NOT EXISTS idx_events_project_status_ts ON events(project_id, status, ts);

CREATE TABLE IF NOT EXISTS limit_rules (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- cost_usd | calls | tokens
  metric TEXT NOT NULL,
  -- hour | day | month
  window TEXT NOT NULL,
  threshold REAL NOT NULL,
  -- alert | throttle | block
  action TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS scores (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  event_id TEXT,
  rubric TEXT NOT NULL,
  value REAL NOT NULL,
  max REAL NOT NULL DEFAULT 1.0,
  pass INTEGER,
  reasoning TEXT,
  scored_by TEXT NOT NULL,
  cost_usd REAL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_scores_project ON scores(project_id, created_at);
-- Probe scores by the event they judged: powers the trace-scores join and the online scorer's
-- unscored-events anti-join. Without it both full-scan `scores`.
CREATE INDEX IF NOT EXISTS idx_scores_event ON scores(event_id);
-- Run-scoped case results, already in the listing's order.
CREATE INDEX IF NOT EXISTS idx_scores_run ON scores(run_id, case_index, created_at);
CREATE INDEX IF NOT EXISTS idx_scores_rubric_id ON scores(rubric_id, created_at);
CREATE INDEX IF NOT EXISTS idx_scores_kind ON scores(kind, created_at);
-- The quality read joins scores to events by event_id and windows on the VERDICT's created_at;
-- without this the join degrades to a scan of the scores table per window.
CREATE INDEX IF NOT EXISTS idx_scores_created ON scores(created_at);

CREATE TABLE IF NOT EXISTS benchmarks (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  name TEXT NOT NULL,
  rubric TEXT NOT NULL,
  judge_model TEXT NOT NULL,
  target TEXT,
  dataset_ref TEXT,
  -- JSON array of {input, expected?, output?}
  dataset TEXT,
  -- optional structured rubric for per-dimension judging
  rubric_id TEXT,
  baseline_score REAL,
  created_at TEXT NOT NULL
);

-- Weighted, anchored rubrics.
CREATE TABLE IF NOT EXISTS rubrics (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  name TEXT NOT NULL,
  -- JSON array of {key, description, weight, anchors, floor?}
  dimensions TEXT NOT NULL,
  threshold REAL NOT NULL DEFAULT 0.7,
  created_at TEXT NOT NULL
);

-- Background job queue: enqueue returns immediately; lt-runner serve executes.
CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  payload TEXT,
  status TEXT NOT NULL DEFAULT 'queued',
  -- claims, including ones a crash ended
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3,
  progress TEXT,
  error TEXT,
  result TEXT,
  claimed_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status, created_at);
CREATE INDEX IF NOT EXISTS idx_jobs_project_created ON jobs(project_id, created_at DESC);

-- Named, versioned prompts fetched at runtime by label (e.g. production | staging). Cutting a
-- new version auto-enqueues the linked benchmark; promoting a label is blocked when that
-- benchmark's score regresses against its baseline.
CREATE TABLE IF NOT EXISTS prompts (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  name TEXT NOT NULL,
  -- linked benchmark; its regression check gates promotion
  benchmark_id TEXT,
  -- JSON object: label -> version (e.g. {"production": 3})
  labels TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (project_id, name)
);
CREATE INDEX IF NOT EXISTS idx_prompts_project ON prompts(project_id, name);

-- Immutable prompt versions (one row per cut). `version` is monotonic per prompt.
CREATE TABLE IF NOT EXISTS prompt_versions (
  id TEXT PRIMARY KEY,
  prompt_id TEXT NOT NULL REFERENCES prompts(id),
  version INTEGER NOT NULL,
  content TEXT NOT NULL,
  -- JSON (model, params, variable schema)
  config TEXT,
  -- change note / "commit message"
  note TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (prompt_id, version)
);
CREATE INDEX IF NOT EXISTS idx_prompt_versions_pid ON prompt_versions(prompt_id, version);

CREATE TABLE IF NOT EXISTS benchmark_runs (
  id TEXT PRIMARY KEY,
  benchmark_id TEXT NOT NULL REFERENCES benchmarks(id),
  started_at TEXT NOT NULL,
  finished_at TEXT,
  n_cases INTEGER NOT NULL DEFAULT 0,
  mean_score REAL,
  pass_rate REAL,
  cost_usd REAL,
  status TEXT NOT NULL DEFAULT 'running',
  p50_latency_ms INTEGER,
  p95_latency_ms INTEGER,
  total_tokens INTEGER,
  report TEXT
);

-- DB-backed price book (source of truth; config/pricing.json is the seed). M26 made it a dated,
-- append-only timeline: the identity of a rate has to be (provider, model, effective_from), or
-- a correction overwrites the row that priced last quarter's traffic and no June cost number
-- can ever be defended. The migration off the pre-M26 shape is a named step, not an ALTER —
-- SQLite cannot change a primary key, and Postgres needs a guarded rename; see
-- `schema::migrations`.
CREATE TABLE IF NOT EXISTS model_prices (
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  input_per_mtok REAL NOT NULL,
  output_per_mtok REAL NOT NULL,
  cached_input_per_mtok REAL,
  effective_from TEXT NOT NULL,
  source_url TEXT,
  verified_at TEXT,
  note TEXT,
  PRIMARY KEY (provider, model, effective_from)
);

-- Versioned evaluation datasets, built by hand or sampled from real events.
CREATE TABLE IF NOT EXISTS datasets (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  name TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  frozen INTEGER NOT NULL DEFAULT 0,
  source TEXT,
  created_at TEXT NOT NULL
);
-- The version walk and the fork's "what is the highest version this name already has" read.
CREATE INDEX IF NOT EXISTS idx_datasets_name_version ON datasets(project_id, name, version);

CREATE TABLE IF NOT EXISTS dataset_items (
  id TEXT PRIMARY KEY,
  dataset_id TEXT NOT NULL REFERENCES datasets(id),
  input TEXT NOT NULL,
  output TEXT,
  expected TEXT,
  context TEXT,
  -- JSON array
  tags TEXT,
  source_event_id TEXT,
  -- JSON {method, redactions}
  anonymization TEXT
);
CREATE INDEX IF NOT EXISTS idx_dataset_items_ds ON dataset_items(dataset_id);
-- Dedupe's lookup: the fingerprints already in the target set.
CREATE INDEX IF NOT EXISTS idx_dataset_items_hash ON dataset_items(dataset_id, input_hash);

-- Normalized revenue: the revenue analog of events' cost. Synced from a billing provider
-- (Stripe/Polar) or posted by hand; netted against LLM cost per customer/product.
CREATE TABLE IF NOT EXISTS revenue_events (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- stripe | polar | manual
  source TEXT NOT NULL DEFAULT 'manual',
  -- provider invoice/charge/order id (idempotency)
  external_id TEXT,
  customer_id TEXT,
  product_id TEXT,
  -- non-negative magnitude; sign derived from kind
  amount_usd REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'USD',
  -- subscription | one_time | usage | refund
  kind TEXT NOT NULL DEFAULT 'one_time',
  -- subscription recognition window
  period_start TEXT,
  period_end TEXT,
  ts TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_revenue_project_ts ON revenue_events(project_id, ts);
CREATE INDEX IF NOT EXISTS idx_revenue_customer ON revenue_events(customer_id);

-- Collective Model Intelligence: privacy-safe, aggregate-only digest entries contributed by
-- other LightTrack instances. No raw text, no project/customer ids — only public model
-- identities plus aggregate quality/cost/latency. The primary key makes a re-contribution an
-- upsert in place rather than a second vote from the same source.
CREATE TABLE IF NOT EXISTS collective_entries (
  -- opaque, non-reversible source id (a hash)
  contributor_id TEXT NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  -- coarse bucket from a fixed vocabulary
  task_type TEXT NOT NULL,
  -- mean score 0..1
  quality REAL NOT NULL,
  pass_rate REAL NOT NULL,
  -- per case
  avg_cost_usd REAL NOT NULL,
  p50_latency_ms INTEGER,
  p95_latency_ms INTEGER,
  n_runs INTEGER NOT NULL DEFAULT 0,
  n_cases INTEGER NOT NULL DEFAULT 0,
  received_at TEXT NOT NULL,
  PRIMARY KEY (contributor_id, provider, model, task_type)
);
CREATE INDEX IF NOT EXISTS idx_collective_model ON collective_entries(provider, model, task_type);
-- Retention-narrowed leaderboard reads. Timestamps are fixed-width RFC3339(Nanos,Z), so the
-- string range is a correct chronological one.
CREATE INDEX IF NOT EXISTS idx_collective_received ON collective_entries(received_at);

-- Cloud→device relay queue (docs/RELAY.md): apps enqueue action_type + JSON params; the
-- enrolled local device leases due tasks over outbound HTTPS, runs them against its local
-- action library, and settles each with succeeded | failed | deferred.
-- Prompts/tools/credentials live only on the device — the payload carries parameters, never
-- instructions.
CREATE TABLE IF NOT EXISTS relay_tasks (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- originator tag (which app enqueued it)
  source TEXT,
  -- resolved against the device's library
  action_type TEXT NOT NULL,
  -- JSON params
  payload TEXT,
  -- queued | leased | succeeded | dead
  status TEXT NOT NULL DEFAULT 'queued',
  -- consumed on lease; Deferred hands one back
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 4,
  -- 5h — one Claude subscription window
  retry_interval_secs INTEGER NOT NULL DEFAULT 18000,
  idempotency_key TEXT,
  -- which device holds/held the lease (a `devices.id`)
  device TEXT,
  -- expired lease => reclaimable (or dead)
  lease_deadline TEXT,
  -- not leasable before this (retry backoff)
  next_attempt_at TEXT NOT NULL,
  result TEXT,
  error TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_relay_due ON relay_tasks(status, next_attempt_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_relay_idem ON relay_tasks(project_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relay_lease ON relay_tasks(status, lease_deadline);

-- Standing margin guardrails (M4): the policies the forecast sweep turns into limit rules.
-- `trigger` and `action` are JSON because both are open sum types that gain variants; this is
-- config read once per sweep, never on the ingest path, so schema stability beats shredded
-- columns.
CREATE TABLE IF NOT EXISTS margin_policies (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- PolicyTrigger: {"below_pct":20} | "negative_margin" | {"erosion_eta_days":5}
  trigger_json TEXT NOT NULL,
  min_cost_usd REAL NOT NULL DEFAULT 0,
  -- PolicyAction: "warn" | {"cap_to_revenue":{"factor":0.8}} | "throttle" | "block"
  action_json TEXT NOT NULL,
  cooldown_secs INTEGER NOT NULL DEFAULT 3600,
  expiry_secs INTEGER NOT NULL DEFAULT 86400,
  enabled INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_margin_policies_project ON margin_policies(project_id);

-- Recurring workloads as rows (M7). Before this, recurrence lived either in a benchmark's
-- target or in a daemon's --interval flag, so nothing could enumerate it.
CREATE TABLE IF NOT EXISTS schedules (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- JobKind wire literal (bench_run | score_events | ...)
  kind TEXT NOT NULL,
  -- enqueued verbatim as the job's payload
  payload TEXT,
  interval_secs INTEGER NOT NULL,
  next_due TEXT NOT NULL,
  last_job_id TEXT,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_schedules_due ON schedules(enabled, next_due);
CREATE INDEX IF NOT EXISTS idx_schedules_project ON schedules(project_id);

-- Who may lease relay tasks, and what each one can actually run (M18). The relay used to have
-- exactly one anonymous device: a shared key authorized every lease and the `device` written
-- onto a task was whatever the client asserted, so identity was un-revocable and routing was
-- blind. The raw `ltd_<prefix>_<secret>` is shown once and never stored.
CREATE TABLE IF NOT EXISTS devices (
  id TEXT PRIMARY KEY,
  -- NULL = operator-wide: serves every project
  project_id TEXT,
  name TEXT NOT NULL,
  key_prefix TEXT NOT NULL,
  -- the api_keys scheme verbatim ("<salt>:<sha256hex>")
  key_hash TEXT NOT NULL,
  -- JSON array of action types / "<ns>/*" prefixes; [] = everything
  capabilities TEXT NOT NULL DEFAULT '[]',
  -- liveness: there is no inbound path to a device
  last_seen_at TEXT,
  agent_version TEXT,
  created_at TEXT NOT NULL,
  -- a flag, not a delete: past tasks still resolve
  revoked INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_prefix ON devices(key_prefix);
CREATE INDEX IF NOT EXISTS idx_devices_project ON devices(project_id);

-- Every alert this deployment has fired (M3). Before this table an alert was a `tracing::warn!`
-- and a HashMap entry: dedup reset on restart, each replica alerted independently, and nothing
-- recorded whether delivery landed. `dedup_key` + `fired_at` is the cooldown gate, decided in
-- one transaction so two replicas produce one alert.
CREATE TABLE IF NOT EXISTS alerts (
  id TEXT PRIMARY KEY,
  -- NULL = a deployment-wide condition
  project_id TEXT,
  -- AlertKind wire literal (limit_breach | score_drop | ...)
  kind TEXT NOT NULL,
  -- the logical identity the cooldown dedups on
  dedup_key TEXT NOT NULL,
  -- info | warning | critical
  severity TEXT NOT NULL,
  -- the same body the channel delivered
  payload TEXT,
  fired_at TEXT NOT NULL,
  -- JSON array of {channel_id, ok, status, at}
  delivered TEXT,
  acked_at TEXT,
  acked_by TEXT,
  -- what came of it (responder diagnosis / note)
  resolution TEXT
);
-- The dedup gate: one range seek, not a scan.
CREATE INDEX IF NOT EXISTS idx_alerts_dedup ON alerts(dedup_key, fired_at);
CREATE INDEX IF NOT EXISTS idx_alerts_fired ON alerts(fired_at);
CREATE INDEX IF NOT EXISTS idx_alerts_project ON alerts(project_id, fired_at);

-- Where an alert goes. `project_id IS NULL` is a global channel — the shape the
-- env-configured destinations have always had, which is why those are synthesised at startup
-- and never stored.
CREATE TABLE IF NOT EXISTS alert_channels (
  id TEXT PRIMARY KEY,
  -- NULL = global (receives every project's alerts)
  project_id TEXT,
  -- webhook | ntfy | email
  kind TEXT NOT NULL,
  -- URL (webhook/ntfy) or address (email)
  target TEXT NOT NULL,
  -- sha256(secret): the derived HMAC signing key
  secret_hash TEXT,
  -- kept live through a rotation
  prev_secret_hash TEXT,
  -- info | warning | critical
  min_severity TEXT NOT NULL,
  -- JSON array of AlertKind; NULL = every kind
  kinds TEXT,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alert_channels_project ON alert_channels(project_id);

-- What THIS instance pushed to a collective hub, and what the hub said back (M22). The digest
-- BODY is deliberately absent: only the hash the gate skips an unchanged re-push by, and the
-- counts. `hub_url_hash` is hashed for the same reason the contributor id is — a ledger an
-- operator shows someone should not be where a private hub's address leaks from.
CREATE TABLE IF NOT EXISTS collective_contributions (
  id TEXT PRIMARY KEY,
  -- `h-` + 12 hex of sha256(normalized hub URL)
  hub_url_hash TEXT NOT NULL,
  -- what the HUB filed it under; may differ from ours
  contributor_id_as_acked TEXT,
  schema_version INTEGER NOT NULL,
  -- when the digest was BUILT
  generated_at TEXT NOT NULL,
  entries_count INTEGER NOT NULL,
  -- the consent envelope, at rest
  projects_included INTEGER NOT NULL,
  projects_excluded INTEGER NOT NULL,
  -- the hash gate; excludes generated_at by construction
  digest_sha256 TEXT NOT NULL,
  -- the hub's answer verbatim, or the failure
  ack TEXT,
  -- sent | rejected | failed
  status TEXT NOT NULL,
  -- when the push happened
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_contributions_created ON collective_contributions(created_at);
CREATE INDEX IF NOT EXISTS idx_contributions_hub ON collective_contributions(hub_url_hash, created_at);

-- What a person said about one subject (M11). The subject is TWO columns rather than one
-- "kind:id" string, for the reason M9 split `scores.rubric`: a column carrying several
-- encodings is a column nothing can index or join on.
CREATE TABLE IF NOT EXISTS labels (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- event | dataset_item | score
  subject_kind TEXT NOT NULL,
  subject_id TEXT NOT NULL,
  -- NULL = a general quality opinion
  rubric_id TEXT,
  -- 0..1, comparable with scores.value/max
  value REAL NOT NULL,
  -- an explicit human call; NULL = derive from value
  pass INTEGER,
  -- JSON array of ScoreDim; read whole, never filtered
  dimensions TEXT,
  -- who said so: what makes a result auditable
  labeler TEXT NOT NULL,
  note TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_labels_subject ON labels(subject_kind, subject_id);
CREATE INDEX IF NOT EXISTS idx_labels_project ON labels(project_id, created_at);
CREATE INDEX IF NOT EXISTS idx_labels_rubric ON labels(rubric_id, created_at);

-- One completed judge↔human calibration (M11). Append-only: a re-measurement is a new row.
CREATE TABLE IF NOT EXISTS calibrations (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  -- canonical [provider/]model
  judge TEXT NOT NULL,
  -- NULL = the freeform calibration; matched IS NULL
  rubric_id TEXT,
  dataset_id TEXT,
  dataset_version INTEGER,
  kappa REAL NOT NULL,
  pearson REAL NOT NULL,
  mae REAL NOT NULL,
  rmse REAL NOT NULL,
  -- so trust on 12 cases reads as trust on 12 cases
  n INTEGER NOT NULL,
  -- stored beside `kappa` so raising the bar later cannot silently re-verdict what was already
  -- measured
  kappa_bar REAL NOT NULL,
  trusted INTEGER NOT NULL,
  created_at TEXT NOT NULL
);
-- The lookup every gate makes: exactly one (project, judge, rubric) pair, newest first.
CREATE INDEX IF NOT EXISTS idx_calibrations_key ON calibrations(project_id, judge, rubric_id, created_at);

-- Post-ship columns, applied by crate::sqlite::schema::apply in this order:
--   ALTER TABLE projects ADD COLUMN collective_opt_in INTEGER NOT NULL DEFAULT 0
--   ALTER TABLE projects ADD COLUMN archived_at TEXT
--   ALTER TABLE projects ADD COLUMN require_trusted_judge INTEGER NOT NULL DEFAULT 0
--   ALTER TABLE api_keys ADD COLUMN scopes TEXT
--   ALTER TABLE api_keys ADD COLUMN expires_at TEXT
--   ALTER TABLE events ADD COLUMN name TEXT
--   ALTER TABLE events ADD COLUMN received_at TEXT
--   ALTER TABLE limit_rules ADD COLUMN warn_at REAL
--   ALTER TABLE limit_rules ADD COLUMN scope_kind TEXT
--   ALTER TABLE limit_rules ADD COLUMN scope_value TEXT
--   ALTER TABLE limit_rules ADD COLUMN threshold_json TEXT
--   ALTER TABLE limit_rules ADD COLUMN escalation_json TEXT
--   ALTER TABLE limit_rules ADD COLUMN escalated_until TEXT
--   ALTER TABLE limit_rules ADD COLUMN origin TEXT
--   ALTER TABLE limit_rules ADD COLUMN expires_at TEXT
--   ALTER TABLE scores ADD COLUMN detail TEXT
--   ALTER TABLE scores ADD COLUMN run_id TEXT
--   ALTER TABLE scores ADD COLUMN case_index INTEGER
--   ALTER TABLE scores ADD COLUMN rubric_id TEXT
--   ALTER TABLE scores ADD COLUMN kind TEXT
--   ALTER TABLE rubrics ADD COLUMN version INTEGER NOT NULL DEFAULT 1
--   ALTER TABLE rubrics ADD COLUMN supersedes TEXT
--   ALTER TABLE jobs ADD COLUMN failures INTEGER NOT NULL DEFAULT 0
--   ALTER TABLE jobs ADD COLUMN stale_reclaims INTEGER NOT NULL DEFAULT 0
--   ALTER TABLE jobs ADD COLUMN project_id TEXT
--   ALTER TABLE prompts ADD COLUMN canary TEXT
--   ALTER TABLE prompts ADD COLUMN label_history TEXT
--   ALTER TABLE datasets ADD COLUMN parent_id TEXT
--   ALTER TABLE dataset_items ADD COLUMN input_hash TEXT
--   ALTER TABLE revenue_events ADD COLUMN amount_minor INTEGER
--   ALTER TABLE revenue_events ADD COLUMN fx_rate REAL
--   ALTER TABLE revenue_events ADD COLUMN fx_book_version TEXT
--   ALTER TABLE revenue_events ADD COLUMN converted INTEGER
--   ALTER TABLE collective_entries ADD COLUMN quality_variance REAL
--   ALTER TABLE collective_entries ADD COLUMN judge_provider TEXT
--   ALTER TABLE collective_entries ADD COLUMN rubric_fingerprint TEXT
--   ALTER TABLE collective_entries ADD COLUMN determinism TEXT
--   ALTER TABLE collective_entries ADD COLUMN frozen_dataset TEXT
--   ALTER TABLE collective_entries ADD COLUMN significance_tested TEXT
--   ALTER TABLE relay_tasks ADD COLUMN failures INTEGER NOT NULL DEFAULT 0
--   ALTER TABLE relay_tasks ADD COLUMN stale_reclaims INTEGER NOT NULL DEFAULT 0
--   ALTER TABLE relay_tasks ADD COLUMN lease_fence TEXT
--   ALTER TABLE relay_tasks ADD COLUMN progress TEXT
