//! Rendering the parity matrix. Kept beside the manifest so the document and the data it reports
//! cannot drift: `crates/store/tests/parity_doc.rs` regenerates `docs/PARITY.md` from the three
//! backends' manifests and fails when the checked-in file differs.

use super::{Capabilities, Surface};

/// The generated file's opening line — the guard test uses it to say where the content comes from.
pub const GENERATED_BY: &str =
    "<!-- generated by `cargo test -p lighttrack-store --test parity_doc` — do not edit by hand -->";

/// Render the full parity document for `backends`, in the order given.
///
/// Columns are backends, rows are surfaces, and a cell is either the surface's full semantics or an
/// explicit refusal. There is no third value on purpose: the point of the document is that "partly
/// implemented" is not a state a backend is allowed to be in.
pub fn parity_doc(backends: &[Capabilities]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BY);
    out.push_str("\n\n# Backend parity\n\n");
    out.push_str(
        "What each `Store` backend implements, declared by the backend itself (see\n\
         `crates/store/src/capabilities.rs`). **full** = the conformance suite runs the surface's\n\
         complete semantics against it. **refused** = every method of that surface answers\n\
         `StoreError::Unsupported`, which the API renders as HTTP 501 `unsupported` — and the\n\
         conformance suite asserts that refusal, so a gap can never quietly become an empty page.\n\n",
    );

    out.push_str("| Surface |");
    for b in backends {
        out.push_str(&format!(" {} |", b.backend));
    }
    out.push_str("\n|---|");
    out.push_str(&"---|".repeat(backends.len()));
    out.push('\n');
    for &s in Surface::ALL {
        out.push_str(&format!("| `{}` |", s.as_str()));
        for b in backends {
            out.push_str(if b.has(s) { " full |" } else { " refused |" });
        }
        out.push('\n');
    }

    out.push_str("\n## Atomic admission\n\n");
    out.push_str(
        "Whether a configured usage cap is genuinely enforced under concurrent ingest (one critical\n\
         section) or enforced *on average* (check-then-act, which a burst can outrun). An advisory\n\
         cap that reads as enforced is the failure this row exists to name.\n\n",
    );
    out.push_str("| Backend | admission |\n|---|---|\n");
    for b in backends {
        out.push_str(&format!(
            "| {} | {} |\n",
            b.backend,
            if b.atomic_admission {
                "atomic — the cap holds"
            } else {
                "**advisory** — a concurrent burst can exceed the cap"
            }
        ));
    }

    out.push_str("\n## Methods per surface\n\n");
    for &s in Surface::ALL {
        out.push_str(&format!("- **`{}`** — ", s.as_str()));
        let names: Vec<String> = s.methods().iter().map(|m| format!("`{m}`")).collect();
        out.push_str(&names.join(", "));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_refused_surface_renders_as_refused_not_absent() {
        let doc = parity_doc(&[Capabilities::new(
            "only-core",
            &[Surface::EventsCore],
            false,
        )]);
        assert!(doc.contains("| `events_core` | full |"));
        assert!(
            doc.contains("| `relay` | refused |"),
            "an unimplemented surface must appear as an explicit refusal, not be omitted"
        );
        assert!(doc.contains("**advisory**"));
        // Every surface gets a row: a matrix that silently drops one is how a gap goes unnoticed.
        for s in Surface::ALL {
            assert!(doc.contains(&format!("| `{}` |", s.as_str())), "{s:?} row");
        }
    }
}
