//! The BigQuery renderer.
//!
//! BigQuery is an **analytical mirror**, not a `Store` backend: no code in this workspace opens a
//! BigQuery connection, and the file this renders is what an operator applies to load LightTrack
//! data into a warehouse. It was the worst-drifted of the three DDLs before M14 (a fraction of the
//! tables, missing columns, native `TIMESTAMP` against the fixed-width-string invariant); rendering
//! it from the same model is what stops it drifting again.
//!
//! Two type decisions, recorded in `docs/DECISIONS.md`:
//! * `Ts → STRING`. The store writes fixed-width `RFC3339(Nanos, Z)` and every range filter in the
//!   product is a string comparison over that format. A native `TIMESTAMP` would give the warehouse
//!   different ordering and different boundary semantics from the two backends the tests run on.
//! * `Json → STRING`. The app writes serialized text — including the empty string a legacy row can
//!   carry — which BigQuery's `JSON` type rejects on load.
//!
//! BigQuery has no secondary indexes and no `PRIMARY KEY` enforcement, so neither is rendered;
//! partitioning and clustering carry the same read patterns instead.

use super::model::{Dialect, Table};
use super::render::{column_ddl, comment};

pub const GENERATED_BY: &str =
    "-- generated by `cargo test -p lighttrack-store --test schema_doc` — do not edit by hand.\n\
     -- The source of truth is the declarative model in crates/store/src/schema/tables/.\n\
     -- Regenerate with `UPDATE_SCHEMA_SQL=1 cargo test -p lighttrack-store --test schema_doc`.";

pub fn create_table(t: &Table) -> String {
    let mut out = String::new();
    out.push_str(&comment(t.doc, ""));
    out.push_str(&format!(
        "CREATE TABLE IF NOT EXISTS `${{DATASET}}.{}` (\n",
        t.name
    ));
    // Every column, including the post-ship ones: a warehouse table is loaded, not migrated in
    // place, so there is no "already exists" case to widen around.
    let parts: Vec<String> = t
        .columns
        .iter()
        .map(|c| {
            let mut p = comment(c.doc, "  ");
            p.push_str(&format!("  {}", column_ddl(c, Dialect::BigQuery)));
            p
        })
        .collect();
    out.push_str(&super::render_sqlite::join_ddl(&parts));
    out.push_str("\n)");
    if let Some(p) = t.bq_partition {
        out.push_str(&format!("\nPARTITION BY {p}"));
    }
    if let Some(c) = t.bq_cluster {
        out.push_str(&format!("\nCLUSTER BY {c}"));
    }
    out.push(';');
    out
}

/// The whole checked-in `schema/bigquery/001_init.sql`.
pub fn ddl_file() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BY);
    out.push_str("\n--\n");
    out.push_str(
        "-- LightTrack analytical mirror (BigQuery). Replace ${DATASET} (e.g.\n\
         -- `your-project.lighttrack`). Timestamps are STRING, holding fixed-width\n\
         -- RFC3339(Nanos,Z) exactly as the operational stores write them, so a string range\n\
         -- filter here means what it means there. JSON columns are STRING for the same reason:\n\
         -- the app writes serialized text. BigQuery enforces no keys and has no secondary\n\
         -- indexes, so partitioning and clustering carry the read patterns instead.\n",
    );
    for t in super::tables::all() {
        out.push('\n');
        out.push_str(&create_table(t));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::tables;

    /// The invariant BigQuery used to break: a native `TIMESTAMP` column.
    #[test]
    fn no_native_timestamp_column_is_rendered() {
        let doc = ddl_file();
        for line in doc.lines() {
            assert!(
                !line.contains(" TIMESTAMP"),
                "fixed-width RFC3339 strings, not native timestamps: {line}"
            );
        }
    }

    /// Post-ship columns must appear here — a load target is created whole, never migrated.
    #[test]
    fn a_post_ship_column_is_in_the_created_table() {
        let sql = create_table(&tables::EVENTS);
        assert!(sql.contains("received_at STRING"));
        assert!(sql.contains("name STRING"));
    }

    /// Every table the model declares reaches the warehouse. The pre-M14 file had a third of them.
    #[test]
    fn every_table_is_present() {
        let doc = ddl_file();
        for t in tables::all() {
            assert!(
                doc.contains(&format!("`${{DATASET}}.{}`", t.name)),
                "{} is missing from the BigQuery mirror",
                t.name
            );
        }
    }
}
