//! The Postgres renderer.
//!
//! Everything the file emits is idempotent against an already-applied database: `CREATE … IF NOT
//! EXISTS`, `ADD COLUMN IF NOT EXISTS`, and the two [`super::migrations::PG_RAW`] blocks, which
//! guard themselves on `information_schema` / `pg_index` rather than on a version counter.

use super::migrations;
use super::model::{Dialect, Index, Table};
use super::render::{column_ddl, comment};
use super::render_sqlite::join_ddl;

pub const GENERATED_BY: &str =
    "-- generated by `cargo test -p lighttrack-store --test schema_doc` — do not edit by hand.\n\
     -- The source of truth is the declarative model in crates/store/src/schema/tables/.\n\
     -- Regenerate with `UPDATE_SCHEMA_SQL=1 cargo test -p lighttrack-store --test schema_doc`.";

pub fn create_table(t: &Table) -> String {
    let mut out = String::new();
    out.push_str(&comment(t.doc, ""));
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS {} (\n", t.name));
    let mut parts: Vec<String> = Vec::new();
    for c in t.base_columns() {
        let mut p = String::new();
        p.push_str(&comment(c.doc, "  "));
        p.push_str(&format!("  {}", column_ddl(c, Dialect::Postgres)));
        parts.push(p);
    }
    if !t.primary_key.is_empty() {
        parts.push(format!("  PRIMARY KEY ({})", t.primary_key.join(", ")));
    }
    for u in t.unique {
        parts.push(format!("  UNIQUE ({u})"));
    }
    out.push_str(&join_ddl(&parts));
    out.push_str("\n);");
    out
}

pub fn create_index(t: &Table, i: &Index) -> String {
    let cols = i.pg_columns.unwrap_or(i.columns);
    let mut s = if i.unique {
        String::from("CREATE UNIQUE INDEX IF NOT EXISTS ")
    } else {
        String::from("CREATE INDEX IF NOT EXISTS ")
    };
    s.push_str(&format!("{} ON {}({cols})", i.name, t.name));
    if let Some(p) = i.predicate {
        s.push_str(&format!(" WHERE {p}"));
    }
    s
}

/// The whole checked-in `schema/postgres/001_init.sql`, applied top to bottom on every boot.
pub fn ddl_file() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BY);
    out.push_str("\n--\n");
    out.push_str(
        "-- LightTrack Postgres store. Ports the reference model: INTEGER -> BIGINT; REAL ->\n\
         -- DOUBLE PRECISION; the reserved word \"window\" quoted. Timestamps stay TEXT\n\
         -- (fixed-width RFC3339(Nanos,Z)) so string range filters and ORDER BY match SQLite.\n\
         -- The whole file is idempotent: re-applying it against a live database is a no-op.\n",
    );

    out.push_str("\n-- 1. Tables, with the columns they shipped with.\n");
    for t in super::tables::all() {
        out.push('\n');
        out.push_str(&create_table(t));
        out.push('\n');
    }

    out.push_str(
        "\n-- 2. Post-ship columns. Every widening precedes every index below, so an index over a\n\
         -- column an older deployment does not have yet can never be attempted first.\n\n",
    );
    for stmt in migrations::add_columns(Dialect::Postgres) {
        out.push_str(&stmt);
        out.push_str(";\n");
    }

    out.push_str("\n-- 3. Migrations no declarative form expresses.\n");
    for raw in migrations::PG_RAW {
        out.push_str(&format!("\n-- [{}]\n", raw.name));
        out.push_str(raw.sql);
        out.push('\n');
    }

    out.push_str("\n-- 4. Indexes.\n\n");
    for t in super::tables::all() {
        for i in t.indexes.iter().filter(|i| i.serves(Dialect::Postgres)) {
            out.push_str(&comment(i.doc, ""));
            out.push_str(&create_index(t, i));
            out.push_str(";\n");
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::tables;

    #[test]
    fn every_widening_is_conditional() {
        for stmt in migrations::add_columns(Dialect::Postgres) {
            assert!(
                stmt.contains("ADD COLUMN IF NOT EXISTS"),
                "not idempotent: {stmt}"
            );
        }
    }

    /// Nothing in the generated file may create a table or index unconditionally: the file is
    /// re-applied on every boot of every deployment.
    #[test]
    fn the_file_is_idempotent_by_construction() {
        for line in ddl_file().lines() {
            let l = line.trim();
            if l.starts_with("CREATE TABLE") || l.starts_with("CREATE INDEX") {
                assert!(l.contains("IF NOT EXISTS"), "not idempotent: {l}");
            }
            if l.starts_with("CREATE UNIQUE INDEX") {
                assert!(l.contains("IF NOT EXISTS"), "not idempotent: {l}");
            }
        }
    }

    /// The M26 primary-key rewrite survives verbatim — it is correct because of how it is written.
    #[test]
    fn the_m26_key_rewrite_is_carried_verbatim() {
        let doc = ddl_file();
        assert!(doc.contains("DO $m26pk$"));
        assert!(doc.contains("PRIMARY KEY (provider, model, effective_from)"));
        assert!(doc.contains("RENAME COLUMN effective_date TO effective_from"));
    }

    #[test]
    fn the_windowed_accounting_index_is_the_expression_the_queries_use() {
        let idx = tables::EVENTS
            .indexes
            .iter()
            .find(|i| i.name == "idx_events_project_received")
            .expect("idx");
        assert!(
            create_index(&tables::EVENTS, idx).contains("(project_id, COALESCE(received_at, ts))")
        );
    }

    #[test]
    fn booleans_that_postgres_shipped_as_bigint_stay_bigint() {
        let sql = create_table(&tables::PROJECTS);
        assert!(
            sql.contains("enabled BIGINT NOT NULL DEFAULT 1"),
            "widening projects.enabled would change what sqlx decodes: {sql}"
        );
        assert!(create_table(&tables::SCHEDULES).contains("enabled BOOLEAN NOT NULL DEFAULT TRUE"));
    }
}
