//! The SQLite renderer — the reference dialect.

use super::migrations;
use super::model::{Dialect, Index, Table};
use super::render::{column_ddl, comment};

pub const GENERATED_BY: &str =
    "-- generated by `cargo test -p lighttrack-store --test schema_doc` — do not edit by hand.\n\
     -- The source of truth is the declarative model in crates/store/src/schema/tables/.\n\
     -- Regenerate with `UPDATE_SCHEMA_SQL=1 cargo test -p lighttrack-store --test schema_doc`.";

pub fn create_table(t: &Table) -> String {
    let mut out = String::new();
    out.push_str(&comment(t.doc, ""));
    out.push_str(&format!("CREATE TABLE IF NOT EXISTS {} (\n", t.name));
    let base: Vec<_> = t.base_columns().collect();
    let mut parts: Vec<String> = Vec::new();
    for c in &base {
        let mut p = String::new();
        p.push_str(&comment(c.doc, "  "));
        p.push_str(&format!("  {}", column_ddl(c, Dialect::Sqlite)));
        parts.push(p);
    }
    if !t.primary_key.is_empty() {
        parts.push(format!("  PRIMARY KEY ({})", t.primary_key.join(", ")));
    }
    for u in t.unique {
        parts.push(format!("  UNIQUE ({u})"));
    }
    out.push_str(&join_ddl(&parts));
    out.push_str("\n);");
    out
}

/// Join the column fragments with `,\n`, keeping each fragment's leading comment lines out of the
/// comma dance (a comma after a `--` line would be part of the comment).
pub(super) fn join_ddl(parts: &[String]) -> String {
    let mut out = String::new();
    for (i, p) in parts.iter().enumerate() {
        if i > 0 {
            out.push_str(",\n");
        }
        out.push_str(p);
    }
    out
}

pub fn create_index(t: &Table, i: &Index) -> String {
    let mut s = String::new();
    if i.unique {
        s.push_str("CREATE UNIQUE INDEX IF NOT EXISTS ");
    } else {
        s.push_str("CREATE INDEX IF NOT EXISTS ");
    }
    s.push_str(&format!("{} ON {}({})", i.name, t.name, i.columns));
    if let Some(p) = i.predicate {
        s.push_str(&format!(" WHERE {p}"));
    }
    s
}

/// The whole checked-in `schema/sqlite/001_init.sql`.
///
/// It is only the `CREATE` half: the post-ship widenings are applied by
/// `crate::sqlite::schema::apply` from the same model, so a fresh database and a migrated one end
/// up with the same columns without the file having to state them twice.
pub fn ddl_file() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_BY);
    out.push_str("\n--\n");
    out.push_str(
        "-- LightTrack local store (SQLite), the reference schema. Columns added after a table\n\
         -- shipped are NOT written here: they are applied as ALTER TABLE … ADD COLUMN by\n\
         -- crate::sqlite::schema::apply, from the same model, so a database created today and one\n\
         -- created five milestones ago converge on the same shape.\n",
    );
    out.push_str("PRAGMA journal_mode = WAL;\n");
    for t in super::tables::all() {
        out.push('\n');
        out.push_str(&create_table(t));
        out.push('\n');
        for i in t.indexes.iter().filter(|i| i.serves(Dialect::Sqlite)) {
            out.push_str(&comment(i.doc, ""));
            out.push_str(&create_index(t, i));
            out.push_str(";\n");
        }
    }
    out.push_str(
        "\n-- Post-ship columns, applied by crate::sqlite::schema::apply in this order:\n",
    );
    for stmt in migrations::add_columns(Dialect::Sqlite) {
        out.push_str(&format!("--   {stmt}\n"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::tables;

    #[test]
    fn a_created_table_carries_only_its_original_columns() {
        let sql = create_table(&tables::EVENTS);
        assert!(sql.contains("project_id TEXT NOT NULL"));
        assert!(
            !sql.contains("received_at TEXT"),
            "a post-ship column belongs in the ALTER list, not the CREATE"
        );
    }

    #[test]
    fn a_composite_key_is_rendered_as_a_table_constraint() {
        let sql = create_table(&tables::COLLECTIVE_ENTRIES);
        assert!(sql.contains("PRIMARY KEY (contributor_id, provider, model, task_type)"));
    }

    #[test]
    fn a_partial_unique_index_keeps_its_predicate() {
        let idx = tables::RELAY_TASKS
            .indexes
            .iter()
            .find(|i| i.name == "idx_relay_idem")
            .expect("idx_relay_idem");
        let sql = create_index(&tables::RELAY_TASKS, idx);
        assert_eq!(
            sql,
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_relay_idem ON relay_tasks(project_id, \
             idempotency_key) WHERE idempotency_key IS NOT NULL"
        );
    }
}
