-- generated by `cargo test -p lighttrack-store --test schema_doc` — do not edit by hand.
-- The source of truth is the declarative model in crates/store/src/schema/tables/.
-- Regenerate with `UPDATE_SCHEMA_SQL=1 cargo test -p lighttrack-store --test schema_doc`.
--
-- LightTrack analytical mirror (BigQuery). Replace ${DATASET} (e.g.
-- `your-project.lighttrack`). Timestamps are STRING, holding fixed-width
-- RFC3339(Nanos,Z) exactly as the operational stores write them, so a string range
-- filter here means what it means there. JSON columns are STRING for the same reason:
-- the app writes serialized text. BigQuery enforces no keys and has no secondary
-- indexes, so partitioning and clustering carry the read patterns instead.

-- A tenant. Everything else in the schema hangs off a project id.
CREATE TABLE IF NOT EXISTS `${DATASET}.projects` (
  id STRING NOT NULL,
  name STRING NOT NULL,
  enabled INT64 NOT NULL DEFAULT 1,
  -- none | hash | drop
  redaction STRING NOT NULL DEFAULT 'none',
  created_at STRING NOT NULL,
  -- Consent to include this project's benchmark runs in a collective-network digest. Default
  -- off: contribution is an act, not an inheritance.
  collective_opt_in INT64 NOT NULL DEFAULT 0,
  -- Set by DELETE /v1/projects/:id. Archive, never delete: the events and runs stay.
  archived_at STRING,
  -- The per-project judge-trust policy. OFF by default: turning it on retroactively would block
  -- every existing deployment's gates on the day it upgraded, nothing having been calibrated
  -- yet.
  require_trusted_judge INT64 NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `${DATASET}.api_keys` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  name STRING NOT NULL,
  prefix STRING NOT NULL,
  key_hash STRING NOT NULL,
  created_at STRING NOT NULL,
  last_used_at STRING,
  revoked INT64 NOT NULL DEFAULT 0,
  -- JSON array of ingest|read|manage. NULL on rows written before scopes existed, which read as
  -- the permissive back-compat default (core::decode_scopes).
  scopes STRING,
  -- Fixed-width RFC3339. Past it, the key authenticates as nothing.
  expires_at STRING
);

-- One observed LLM call. The ingest table; everything cost-shaped is a rollup of it.
CREATE TABLE IF NOT EXISTS `${DATASET}.events` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  trace_id STRING,
  span_id STRING,
  parent_span_id STRING,
  ts STRING NOT NULL,
  provider STRING NOT NULL,
  model STRING NOT NULL,
  operation STRING NOT NULL DEFAULT 'chat',
  input_tokens INT64 NOT NULL DEFAULT 0,
  output_tokens INT64 NOT NULL DEFAULT 0,
  cached_input_tokens INT64,
  reasoning_tokens INT64,
  cost_usd FLOAT64,
  latency_ms INT64,
  status STRING NOT NULL DEFAULT 'success',
  error STRING,
  input STRING,
  output STRING,
  -- JSON array
  tags STRING,
  source STRING,
  metadata STRING,
  -- optional use-case / call-site label (rollup key)
  name STRING,
  -- Server-stamped arrival time (fixed-width RFC3339 UTC, like `ts`). `ts` is CLIENT event time
  -- and may be skewed or deliberately backdated; every rolling-window accounting read (limit
  -- admission, the forecast series) keys on `received_at` so one wrong clock cannot move a
  -- budget window. Backfilled to `ts` for rows written before the column existed.
  received_at STRING
)
PARTITION BY DATE(ts)
CLUSTER BY project_id, provider, model;

CREATE TABLE IF NOT EXISTS `${DATASET}.limit_rules` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- cost_usd | calls | tokens
  metric STRING NOT NULL,
  -- hour | day | month
  window STRING NOT NULL,
  threshold FLOAT64 NOT NULL,
  -- alert | throttle | block
  action STRING NOT NULL,
  enabled INT64 NOT NULL DEFAULT 1,
  -- optional soft-warning fraction in (0,1); NULL = no pre-warning
  warn_at FLOAT64,
  -- provider | model | name; NULL = project-wide (unscoped)
  scope_kind STRING,
  -- the scoped dimension value; NULL when unscoped
  scope_value STRING,
  -- Measure-to-act guardrails: a threshold that is not a bare number. All five columns here are
  -- nullable — an existing row reads back as exactly the fixed, human-made, never-expiring
  -- rule it always was.
  threshold_json STRING,
  escalation_json STRING,
  escalated_until STRING,
  origin STRING,
  expires_at STRING
);

CREATE TABLE IF NOT EXISTS `${DATASET}.scores` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  event_id STRING,
  rubric STRING NOT NULL,
  value FLOAT64 NOT NULL,
  max FLOAT64 NOT NULL DEFAULT 1.0,
  pass INT64,
  reasoning STRING,
  -- Structured verdict provenance (core::ScoreDetail) as JSON: per-dimension {value, weight,
  -- floor_hit, floor_hits/floor_of, reasoning[]}, agreement, sample accounting, bias/injection
  -- flags. NULL for scores posted without it. Bounded by ScoreDetail::capped() at the API
  -- boundary.
  detail STRING,
  -- The benchmark run that produced this verdict (NULL for online/ad-hoc scores). With
  -- `case_index` it makes "every case result for run X" a query instead of a created_at guess.
  run_id STRING,
  -- the 1-based case position within that run
  case_index INT64,
  scored_by STRING NOT NULL,
  cost_usd FLOAT64,
  created_at STRING NOT NULL,
  -- Typed verdict identity. `scores.rubric` is one free-text column carrying six encodings, so
  -- nothing downstream could tell a benchmark case from a calibration probe without parsing a
  -- string — and the alerting window keyed on that string, which made every compare cell a
  -- unique key that never accumulated. The legacy label stays verbatim beside these.
  rubric_id STRING,
  kind STRING
)
PARTITION BY DATE(created_at)
CLUSTER BY project_id, rubric;

CREATE TABLE IF NOT EXISTS `${DATASET}.benchmarks` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  name STRING NOT NULL,
  rubric STRING NOT NULL,
  judge_model STRING NOT NULL,
  target STRING,
  dataset_ref STRING,
  -- JSON array of {input, expected?, output?}
  dataset STRING,
  -- optional structured rubric for per-dimension judging
  rubric_id STRING,
  baseline_score FLOAT64,
  created_at STRING NOT NULL
);

-- Weighted, anchored rubrics.
CREATE TABLE IF NOT EXISTS `${DATASET}.rubrics` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  name STRING NOT NULL,
  -- JSON array of {key, description, weight, anchors, floor?}
  dimensions STRING NOT NULL,
  threshold FLOAT64 NOT NULL DEFAULT 0.7,
  created_at STRING NOT NULL,
  -- A rubric edit changes what a score *means*, and nothing recorded that one had happened. A
  -- new version is a new row linked to the old one, never a mutation of it.
  version INT64 NOT NULL DEFAULT 1,
  supersedes STRING
);

-- Background job queue: enqueue returns immediately; lt-runner serve executes.
CREATE TABLE IF NOT EXISTS `${DATASET}.jobs` (
  id STRING NOT NULL,
  type STRING NOT NULL,
  payload STRING,
  status STRING NOT NULL DEFAULT 'queued',
  -- claims, including ones a crash ended
  attempts INT64 NOT NULL DEFAULT 0,
  max_attempts INT64 NOT NULL DEFAULT 3,
  progress STRING,
  error STRING,
  result STRING,
  claimed_at STRING,
  created_at STRING NOT NULL,
  updated_at STRING NOT NULL,
  -- runs that actually failed — the retry budget, kept apart from `attempts`
  failures INT64 NOT NULL DEFAULT 0,
  -- worker deaths (claim held past the stale window)
  stale_reclaims INT64 NOT NULL DEFAULT 0,
  -- The job queue's missing tenant: without it a project key reading GET /v1/jobs saw every
  -- project's payloads. Nullable — NULL is an operator/legacy job, which `Scope::Operator`
  -- sees and no project scope does.
  project_id STRING
);

-- Named, versioned prompts fetched at runtime by label (e.g. production | staging). Cutting a
-- new version auto-enqueues the linked benchmark; promoting a label is blocked when that
-- benchmark's score regresses against its baseline.
CREATE TABLE IF NOT EXISTS `${DATASET}.prompts` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  name STRING NOT NULL,
  -- linked benchmark; its regression check gates promotion
  benchmark_id STRING,
  -- JSON object: label -> version (e.g. {"production": 3})
  labels STRING NOT NULL DEFAULT '{}',
  created_at STRING NOT NULL,
  updated_at STRING NOT NULL,
  -- JSON CanaryPolicy; NULL = the registry still stops observing at promotion
  canary STRING,
  -- JSON array of LabelChange; NULL = no label move recorded here, which is why an auto-revert
  -- with no recorded predecessor does nothing instead of guessing.
  label_history STRING
);

-- Immutable prompt versions (one row per cut). `version` is monotonic per prompt.
CREATE TABLE IF NOT EXISTS `${DATASET}.prompt_versions` (
  id STRING NOT NULL,
  prompt_id STRING NOT NULL,
  version INT64 NOT NULL,
  content STRING NOT NULL,
  -- JSON (model, params, variable schema)
  config STRING,
  -- change note / "commit message"
  note STRING,
  created_at STRING NOT NULL
);

CREATE TABLE IF NOT EXISTS `${DATASET}.benchmark_runs` (
  id STRING NOT NULL,
  benchmark_id STRING NOT NULL,
  started_at STRING NOT NULL,
  finished_at STRING,
  n_cases INT64 NOT NULL DEFAULT 0,
  mean_score FLOAT64,
  pass_rate FLOAT64,
  cost_usd FLOAT64,
  status STRING NOT NULL DEFAULT 'running',
  p50_latency_ms INT64,
  p95_latency_ms INT64,
  total_tokens INT64,
  report STRING
);

-- DB-backed price book (source of truth; config/pricing.json is the seed). M26 made it a dated,
-- append-only timeline: the identity of a rate has to be (provider, model, effective_from), or
-- a correction overwrites the row that priced last quarter's traffic and no June cost number
-- can ever be defended. The migration off the pre-M26 shape is a named step, not an ALTER —
-- SQLite cannot change a primary key, and Postgres needs a guarded rename; see
-- `schema::migrations`.
CREATE TABLE IF NOT EXISTS `${DATASET}.model_prices` (
  provider STRING NOT NULL,
  model STRING NOT NULL,
  input_per_mtok FLOAT64 NOT NULL,
  output_per_mtok FLOAT64 NOT NULL,
  cached_input_per_mtok FLOAT64,
  effective_from STRING NOT NULL,
  source_url STRING,
  verified_at STRING,
  note STRING
);

-- Versioned evaluation datasets, built by hand or sampled from real events.
CREATE TABLE IF NOT EXISTS `${DATASET}.datasets` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  name STRING NOT NULL,
  version INT64 NOT NULL DEFAULT 1,
  frozen INT64 NOT NULL DEFAULT 0,
  source STRING,
  created_at STRING NOT NULL,
  -- The link that makes `version` mean something: a v2 with no parent is just another row that
  -- shares a name. Nullable — a pre-M24 dataset is a v1 with no parent.
  parent_id STRING
);

CREATE TABLE IF NOT EXISTS `${DATASET}.dataset_items` (
  id STRING NOT NULL,
  dataset_id STRING NOT NULL,
  input STRING NOT NULL,
  output STRING,
  expected STRING,
  context STRING,
  -- JSON array
  tags STRING,
  source_event_id STRING,
  -- JSON {method, redactions}
  anonymization STRING,
  -- The normalised-input fingerprint near-duplicate collapse looks up instead of scanning every
  -- stored case's text. Nullable, and dedupe treats NULL as "no match".
  input_hash STRING
);

-- Normalized revenue: the revenue analog of events' cost. Synced from a billing provider
-- (Stripe/Polar) or posted by hand; netted against LLM cost per customer/product.
CREATE TABLE IF NOT EXISTS `${DATASET}.revenue_events` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- stripe | polar | manual
  source STRING NOT NULL DEFAULT 'manual',
  -- provider invoice/charge/order id (idempotency)
  external_id STRING,
  customer_id STRING,
  product_id STRING,
  -- non-negative magnitude; sign derived from kind
  amount_usd FLOAT64 NOT NULL,
  currency STRING NOT NULL DEFAULT 'USD',
  -- subscription | one_time | usage | refund
  kind STRING NOT NULL DEFAULT 'one_time',
  -- subscription recognition window
  period_start STRING,
  period_end STRING,
  ts STRING NOT NULL,
  -- FX provenance: `amount_usd` is derived and a wrong rate makes it wrong. The provider's own
  -- minor-unit figure never needs restating, so keeping it — with the rate, the book version
  -- behind it, and whether a real conversion happened — turns a rate correction into a
  -- reprice instead of a re-ingest. All four are nullable.
  amount_minor INT64,
  fx_rate FLOAT64,
  fx_book_version STRING,
  converted BOOL
);

-- Collective Model Intelligence: privacy-safe, aggregate-only digest entries contributed by
-- other LightTrack instances. No raw text, no project/customer ids — only public model
-- identities plus aggregate quality/cost/latency. The primary key makes a re-contribution an
-- upsert in place rather than a second vote from the same source.
CREATE TABLE IF NOT EXISTS `${DATASET}.collective_entries` (
  -- opaque, non-reversible source id (a hash)
  contributor_id STRING NOT NULL,
  provider STRING NOT NULL,
  model STRING NOT NULL,
  -- coarse bucket from a fixed vocabulary
  task_type STRING NOT NULL,
  -- mean score 0..1
  quality FLOAT64 NOT NULL,
  pass_rate FLOAT64 NOT NULL,
  -- per case
  avg_cost_usd FLOAT64 NOT NULL,
  p50_latency_ms INT64,
  p95_latency_ms INT64,
  n_runs INT64 NOT NULL DEFAULT 0,
  n_cases INT64 NOT NULL DEFAULT 0,
  received_at STRING NOT NULL,
  -- v2: case-weighted variance of quality across the contributor's runs
  quality_variance FLOAT64,
  -- v2: coarse judge family (anthropic|openai|google|unknown|mixed)
  judge_provider STRING,
  -- v2: short one-way hash of the rubric shape (no content leak)
  rubric_fingerprint STRING,
  -- v3 rigor: weakest stamp (exact|best-effort|sampled), NULL = unrecorded
  determinism STRING,
  -- v3 rigor: coverage tag (all|mixed|none), NULL = unknown
  frozen_dataset STRING,
  -- v3 rigor: coverage tag (all|mixed|none), NULL = unknown
  significance_tested STRING
);

-- Cloud→device relay queue (docs/RELAY.md): apps enqueue action_type + JSON params; the
-- enrolled local device leases due tasks over outbound HTTPS, runs them against its local
-- action library, and settles each with succeeded | failed | deferred.
-- Prompts/tools/credentials live only on the device — the payload carries parameters, never
-- instructions.
CREATE TABLE IF NOT EXISTS `${DATASET}.relay_tasks` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- originator tag (which app enqueued it)
  source STRING,
  -- resolved against the device's library
  action_type STRING NOT NULL,
  -- JSON params
  payload STRING,
  -- queued | leased | succeeded | dead
  status STRING NOT NULL DEFAULT 'queued',
  -- consumed on lease; Deferred hands one back
  attempts INT64 NOT NULL DEFAULT 0,
  max_attempts INT64 NOT NULL DEFAULT 4,
  -- 5h — one Claude subscription window
  retry_interval_secs INT64 NOT NULL DEFAULT 18000,
  idempotency_key STRING,
  -- which device holds/held the lease (a `devices.id`)
  device STRING,
  -- expired lease => reclaimable (or dead)
  lease_deadline STRING,
  -- not leasable before this (retry backoff)
  next_attempt_at STRING NOT NULL,
  result STRING,
  error STRING,
  created_at STRING NOT NULL,
  updated_at STRING NOT NULL,
  -- The fenced, renewable lease (M7): `failures` is the retry budget and `stale_reclaims`
  -- counts device deaths, so a laptop that sleeps mid-run no longer burns one of the task's
  -- chances. `lease_fence` is the holding device's identity, compared exactly on
  -- settle/renew/progress; `progress` is its liveness.
  failures INT64 NOT NULL DEFAULT 0,
  stale_reclaims INT64 NOT NULL DEFAULT 0,
  lease_fence STRING,
  progress STRING
);

-- Standing margin guardrails (M4): the policies the forecast sweep turns into limit rules.
-- `trigger` and `action` are JSON because both are open sum types that gain variants; this is
-- config read once per sweep, never on the ingest path, so schema stability beats shredded
-- columns.
CREATE TABLE IF NOT EXISTS `${DATASET}.margin_policies` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- PolicyTrigger: {"below_pct":20} | "negative_margin" | {"erosion_eta_days":5}
  trigger_json STRING NOT NULL,
  min_cost_usd FLOAT64 NOT NULL DEFAULT 0,
  -- PolicyAction: "warn" | {"cap_to_revenue":{"factor":0.8}} | "throttle" | "block"
  action_json STRING NOT NULL,
  cooldown_secs INT64 NOT NULL DEFAULT 3600,
  expiry_secs INT64 NOT NULL DEFAULT 86400,
  enabled INT64 NOT NULL DEFAULT 1
);

-- Recurring workloads as rows (M7). Before this, recurrence lived either in a benchmark's
-- target or in a daemon's --interval flag, so nothing could enumerate it.
CREATE TABLE IF NOT EXISTS `${DATASET}.schedules` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- JobKind wire literal (bench_run | score_events | ...)
  kind STRING NOT NULL,
  -- enqueued verbatim as the job's payload
  payload STRING,
  interval_secs INT64 NOT NULL,
  next_due STRING NOT NULL,
  last_job_id STRING,
  enabled BOOL NOT NULL DEFAULT TRUE,
  created_at STRING NOT NULL
);

-- Who may lease relay tasks, and what each one can actually run (M18). The relay used to have
-- exactly one anonymous device: a shared key authorized every lease and the `device` written
-- onto a task was whatever the client asserted, so identity was un-revocable and routing was
-- blind. The raw `ltd_<prefix>_<secret>` is shown once and never stored.
CREATE TABLE IF NOT EXISTS `${DATASET}.devices` (
  id STRING NOT NULL,
  -- NULL = operator-wide: serves every project
  project_id STRING,
  name STRING NOT NULL,
  key_prefix STRING NOT NULL,
  -- the api_keys scheme verbatim ("<salt>:<sha256hex>")
  key_hash STRING NOT NULL,
  -- JSON array of action types / "<ns>/*" prefixes; [] = everything
  capabilities STRING NOT NULL DEFAULT '[]',
  -- liveness: there is no inbound path to a device
  last_seen_at STRING,
  agent_version STRING,
  created_at STRING NOT NULL,
  -- a flag, not a delete: past tasks still resolve
  revoked BOOL NOT NULL DEFAULT FALSE
);

-- Every alert this deployment has fired (M3). Before this table an alert was a `tracing::warn!`
-- and a HashMap entry: dedup reset on restart, each replica alerted independently, and nothing
-- recorded whether delivery landed. `dedup_key` + `fired_at` is the cooldown gate, decided in
-- one transaction so two replicas produce one alert.
CREATE TABLE IF NOT EXISTS `${DATASET}.alerts` (
  id STRING NOT NULL,
  -- NULL = a deployment-wide condition
  project_id STRING,
  -- AlertKind wire literal (limit_breach | score_drop | ...)
  kind STRING NOT NULL,
  -- the logical identity the cooldown dedups on
  dedup_key STRING NOT NULL,
  -- info | warning | critical
  severity STRING NOT NULL,
  -- the same body the channel delivered
  payload STRING,
  fired_at STRING NOT NULL,
  -- JSON array of {channel_id, ok, status, at}
  delivered STRING,
  acked_at STRING,
  acked_by STRING,
  -- what came of it (responder diagnosis / note)
  resolution STRING
);

-- Where an alert goes. `project_id IS NULL` is a global channel — the shape the
-- env-configured destinations have always had, which is why those are synthesised at startup
-- and never stored.
CREATE TABLE IF NOT EXISTS `${DATASET}.alert_channels` (
  id STRING NOT NULL,
  -- NULL = global (receives every project's alerts)
  project_id STRING,
  -- webhook | ntfy | email
  kind STRING NOT NULL,
  -- URL (webhook/ntfy) or address (email)
  target STRING NOT NULL,
  -- sha256(secret): the derived HMAC signing key
  secret_hash STRING,
  -- kept live through a rotation
  prev_secret_hash STRING,
  -- info | warning | critical
  min_severity STRING NOT NULL,
  -- JSON array of AlertKind; NULL = every kind
  kinds STRING,
  enabled BOOL NOT NULL DEFAULT TRUE,
  created_at STRING NOT NULL
);

-- What THIS instance pushed to a collective hub, and what the hub said back (M22). The digest
-- BODY is deliberately absent: only the hash the gate skips an unchanged re-push by, and the
-- counts. `hub_url_hash` is hashed for the same reason the contributor id is — a ledger an
-- operator shows someone should not be where a private hub's address leaks from.
CREATE TABLE IF NOT EXISTS `${DATASET}.collective_contributions` (
  id STRING NOT NULL,
  -- `h-` + 12 hex of sha256(normalized hub URL)
  hub_url_hash STRING NOT NULL,
  -- what the HUB filed it under; may differ from ours
  contributor_id_as_acked STRING,
  schema_version INT64 NOT NULL,
  -- when the digest was BUILT
  generated_at STRING NOT NULL,
  entries_count INT64 NOT NULL,
  -- the consent envelope, at rest
  projects_included INT64 NOT NULL,
  projects_excluded INT64 NOT NULL,
  -- the hash gate; excludes generated_at by construction
  digest_sha256 STRING NOT NULL,
  -- the hub's answer verbatim, or the failure
  ack STRING,
  -- sent | rejected | failed
  status STRING NOT NULL,
  -- when the push happened
  created_at STRING NOT NULL
);

-- What a person said about one subject (M11). The subject is TWO columns rather than one
-- "kind:id" string, for the reason M9 split `scores.rubric`: a column carrying several
-- encodings is a column nothing can index or join on.
CREATE TABLE IF NOT EXISTS `${DATASET}.labels` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- event | dataset_item | score
  subject_kind STRING NOT NULL,
  subject_id STRING NOT NULL,
  -- NULL = a general quality opinion
  rubric_id STRING,
  -- 0..1, comparable with scores.value/max
  value FLOAT64 NOT NULL,
  -- an explicit human call; NULL = derive from value
  pass BOOL,
  -- JSON array of ScoreDim; read whole, never filtered
  dimensions STRING,
  -- who said so: what makes a result auditable
  labeler STRING NOT NULL,
  note STRING,
  created_at STRING NOT NULL
);

-- One completed judge↔human calibration (M11). Append-only: a re-measurement is a new row.
CREATE TABLE IF NOT EXISTS `${DATASET}.calibrations` (
  id STRING NOT NULL,
  project_id STRING NOT NULL,
  -- canonical [provider/]model
  judge STRING NOT NULL,
  -- NULL = the freeform calibration; matched IS NULL
  rubric_id STRING,
  dataset_id STRING,
  dataset_version INT64,
  kappa FLOAT64 NOT NULL,
  pearson FLOAT64 NOT NULL,
  mae FLOAT64 NOT NULL,
  rmse FLOAT64 NOT NULL,
  -- so trust on 12 cases reads as trust on 12 cases
  n INT64 NOT NULL,
  -- stored beside `kappa` so raising the bar later cannot silently re-verdict what was already
  -- measured
  kappa_bar FLOAT64 NOT NULL,
  trusted BOOL NOT NULL,
  created_at STRING NOT NULL
);
